# Eigenvalues

Sources:

  1) `Linear Algebra : Theory, Intuition, Code` author: Mike X Cohen, publisher: sincXpress

  2)  `No bullshit guide to linear algebra` author: Ivan Savov

  3)  `Matrix Methods for Computational Modeling and Data Analytics` author: Mark Embree, Virginia Tech

**Motivation**

An understanding of this topics seems necessary to deal with methods to iteratively solve matrix equations, singular value decomposition, principal component analysis



## Properties

A square matrix $\mathbf{B}$ is multiplied by some vector $\mathbf{v}$. If the following condition holds

$$
\mathbf{B} \cdot v = \lambda \cdot \mathbf{v}
$$

the vector $\mathbf{v}$ is an eigenvector and the associated scalar $\lambda$ is the corresponding eigenvalue.

If $\mathbf{v}$ is an eigenvector than than any scaled vector $\alpha \cdot \mathbf{v}$ is also an eigenvector:

$$
\mathbf{B} \cdot \alpha \cdot v = \alpha \cdot \mathbf{B} \cdot v = \alpha \cdot \lambda \cdot \mathbf{v}
$$

Usually numerical software packages compute eigenvectors which have unit length ($||\mathbf{v}|| = 1$).

---

A $m \times m$ matrix has `m` eigenvalues and `m` eigenvectors. Eigenvalues are not required to be distinct. The can even be complex for real valued matrices.

The equation $\mathbf{A} \cdot \mathbf{v} = \lambda \mathbf{v}$ may be written in another form:

$$
\mathbf{A} \cdot \mathbf{v} - \lambda \mathbf{v} = \left(\mathbf{A} -  \lambda \cdot \mathbf{I} \right) \cdot \mathbf{v} = \mathbf{0}
$$

Thus matrix $\left(\mathbf{A} -  \lambda \cdot \mathbf{I} \right)$ must be singular and its determinant $\left|\mathbf{A} -  \lambda \cdot \mathbf{I} \right| = 0$.

### numerical example

Compute eigenvalues and eigenvector of a random 3 x 3 matrix.

In general there may be complex eigenvalues 


In [10]:
import numpy as np
import math

# a 3 x 3 matrix which is not singular (choosing an random matrix increases the likelihood, that the matrix is invertible)
Amat = np.random.randn(3,3)

eigen_values, eigen_vectors_mat = np.linalg.eig(Amat)

print(f"Amat :\n{Amat}\n")
print(f"eigen_values      :\n{eigen_values}\n")
print(f"eigen_vectors_mat :\n{eigen_vectors_mat}\n")

Amat :
[[ 0.6591868   0.54580176 -0.4612541 ]
 [ 0.64048071  1.21914289 -0.63622908]
 [ 0.67373345 -0.78855268  0.37384276]]

eigen_values      :
[0.23718098+0.25641578j 0.23718098-0.25641578j 1.7778105 +0.j        ]

eigen_vectors_mat :
[[ 0.27652084+0.24836548j  0.27652084-0.24836548j -0.50132726+0.j        ]
 [ 0.38246447-0.06212397j  0.38246447+0.06212397j -0.83462347+0.j        ]
 [ 0.84363046+0.j          0.84363046-0.j          0.22819871+0.j        ]]



In [3]:
Amat_times_eigvector =  Amat @ eigen_vectors_mat[:,0] 
eigvalue_times_eigvector = eigen_vectors_mat[:,0] * eigen_values[0]

# should be identical (apart from numeric artefacts)
print(f"Amat_times_eigvector    :\n{Amat_times_eigvector}\n")
print(f"eigvalue_times_eigvector:\n{eigvalue_times_eigvector}\n")

Amat_times_eigvector    :
[ 0.40441327+0.1672811j  -0.05590885+0.0782878j  -0.17806591-0.40974717j]

eigvalue_times_eigvector:
[ 0.40441327+0.1672811j  -0.05590885+0.0782878j  -0.17806591-0.40974717j]



## Eigendecomposition & Diagonalization

The eigenvalues of a $m \times m$ matrix $\mathbf{A}$ are denoted $\left(\lambda_1,\ \lambda_2, \ldots,\  \lambda_m \right)$ and the corresponding eigenvectors $\left( \mathbf{v}_1,\ \mathbf{v}_2, \ldots,\  \mathbf{v}_m \right)$.

This results in `m` equations:

$$\begin{gather}
\mathbf{A} \cdot \mathbf{v}_1 = \lambda_1 \cdot \mathbf{v}_1 \\
\mathbf{A} \cdot \mathbf{v}_2 = \lambda_2 \cdot \mathbf{v}_2 \\
\vdots \\
\mathbf{A} \cdot \mathbf{v}_m = \lambda_m \cdot \mathbf{v}_m \\
\end{gather}
$$

Taking the eigenvectors as column vectors of matrix $\mathbf{V}$

$$
\mathbf{V} =
\left[\begin{array}{cccc}
\vdots & \vdots & \ldots & \vdots \\
\mathbf{v}_1 & \mathbf{v}_2 & \ldots & \mathbf{v}_m \\
\vdots & \vdots & \ldots & \vdots \\
\end{array} \right]
$$

a more compact notation is obtained:

$$
\mathbf{A} \cdot \mathbf{V} =
\left[\begin{array}{cccc}
\vdots & \vdots & \ldots & \vdots \\
\lambda_1 \cdot \mathbf{v}_1 & \lambda_2 \cdot \mathbf{v}_2 & \ldots & \lambda_m \cdot \mathbf{v}_m \\
\vdots & \vdots & \ldots & \vdots \\
\end{array} \right] = \mathbf{V} \cdot \mathbf{\Lambda}
$$

The matrix $\mathbf{\Lambda}$ is a diagonal matrix with the eigenvalues as its diagonal entries.

$$
\mathbf{\Lambda} =
\left[\begin{array}{ccccc}
\lambda_1 & 0 & 0 & \ldots & 0 \\
0 & \lambda_2 & 0 & \ldots & 0 \\
\ldots & \ddots & \ldots & \ldots & 0 \\
\ldots & \ddots & \ldots & \ldots & \lambda_m
\end{array} \right]
$$

If all eigenvectors form an independent set the matrix $\mathbf{V}$ has an inverse $\mathbf{V}^{-1}$. It then follows:

$$
\mathbf{V}^{-1} \cdot \mathbf{A} \cdot \mathbf{V} = \mathbf{V}^{-1} \cdot \mathbf{V} \cdot \mathbf{\Lambda} = \mathbf{\Lambda}
$$

Another interesting property is obtained from right multiplication by $\mathbf{V}^{-1}$.

$$
\mathbf{A} = \mathbf{A} \cdot \mathbf{V} \cdot \mathbf{V}^{-1} = \mathbf{V} \cdot \mathbf{\Lambda} \cdot \mathbf{V}^{-1}
$$


A numerical example computes the eigenvalues and eigenvectors of a $3 \times 3$ matrix

$$
\mathbf{A} = \left[\begin{array}{ccc}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{array}\right]
$$

The eigenvalues are returned in a list while the eigenvectors are returned as column vectors of a $3 \times 3$ matrix $\mathbf{V}$.

Then the inverse matrix $\mathbf{V}^{-1}$ is computed to demonstrate that the eigenvector decomposition 

$$
\mathbf{A} = \mathbf{V} \cdot \mathbf{\Lambda} \cdot \mathbf{V}^{-1}
$$

yields the original matrix $\mathbf{A}$ (well almost, apart from numerical inaccuracies).

---




In [7]:
Amat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
lambda_list, Vmat = np.linalg.eig(Amat)
# convert list of eigenvalues into a diagonal matrix 
lambda_mat = np.diag(lambda_list)

# compute the inverse of the eigen vector matrix (required to demonstrate the validity of the eigenvector decomposition)
Vmat_inv = np.linalg.inv(Vmat)
Amat_from_diagonalisation = Vmat @ lambda_mat @ Vmat_inv

print(f"Amat        :\n{Amat}\n") 
print(f"lambda_mat  :\n{lambda_mat}\n")
print(f"Vmat        :\n{Vmat}\n")
print(f"Vmat_inv    :\n{Vmat_inv}\n")
print(f"Amat_from_diagonalisation :\n{Amat_from_diagonalisation}\n")                         

Amat        :
[[1 2 3]
 [4 5 6]
 [7 8 9]]

lambda_mat  :
[[ 1.61168440e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.11684397e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.30367773e-15]]

Vmat        :
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]

Vmat_inv    :
[[-0.48295226 -0.59340999 -0.70386772]
 [-0.91788599 -0.24901003  0.41986593]
 [ 0.40824829 -0.81649658  0.40824829]]

Amat_from_diagonalisation :
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]



## Special properties of symmetric matrices

1) orthogonal eigenvectors

2) real eigenvalues

**proof** (orthogonality of eigenvectors)

$\lambda_1$ and $\lambda_2$ denote distinct eigenvalues with corresponding eigenvectors $\mathbf{v}_1$ and $\mathbf{v}_2$ .

$\mathbf{A} = \mathbf{A}^T$ 

$$\begin{gather}
\lambda_1 \cdot \mathbf{v}^T_1 \cdot \mathbf{v}_2 = \left(\mathbf{A} \cdot \mathbf{v}_1 \right)^T \cdot \mathbf{v}_2 = \mathbf{v}^T \cdot \mathbf{A}^T \cdot \mathbf{v}_2 \\
\ = \mathbf{v}^T \cdot \lambda_2 \cdot \mathbf{v}_2 = \lambda_2 \cdot \mathbf{v}^T \cdot \mathbf{v}_2\\
\ \to \\
\underbrace{\left(\lambda_1 - \lambda_2 \right)}_{\neq 0} \cdot \underbrace{\mathbf{v}^T_1 \cdot \mathbf{v}_2}_{0} = 0
\end{gather}
$$

Using these orthogonal eigenvector (of a symmetric matrix) as column vectors of a matrix $\mathbf{V}$ the matrix product 

$$
\mathbf{V}^T \cdot \mathbf{V} = \mathbf{D}
$$

is a diagonal matrix. Moreover if the eigenvectors are <ins>normalised</ins> the matrix product yields the identity matrix.

$$
\mathbf{V}^T \cdot \mathbf{V} = \mathbf{I}
$$

Obviously 

$$
\mathbf{V}^T  = \mathbf{V}^{-1}
$$

---

**proof** (all eigenvalues of a real symmetric matrix are real)

Due to its symmetry $\mathbf{A}^T = \mathbf{A}$. Since the matrix is real we have $\mathbf{S}^* = \mathbf{S}$. Moreover we have $\mathbf{S}^{*T} = \mathbf{S}$

Let $\lambda, \mathbf{v}$ denote an eigenvalue and its eigenvector (unit length). 

$$\begin{gather}
\lambda = \lambda \cdot \mathbf{v}^{*T} \cdot \mathbf{v} = \mathbf{v}^{*T} \cdot \lambda \cdot \mathbf{v} = \mathbf{v}^{*T} \cdot \mathbf{A} \cdot \mathbf{v} \\
\mathbf{v}^{*T} \cdot \mathbf{A}^{*T} \cdot \mathbf{v} = \left(\mathbf{A} \cdot \mathbf{v}\right)^{*T} \cdot \mathbf{v} = \lambda^* \cdot \mathbf{v}^{*T} \cdot \mathbf{v}
\to \\
\lambda = \lambda^* 
\end{gather}
$$

So eigenvalue $\lambda$ must be real.


---


## Summary : Properties of symmetrix real matrix

Matrix $\mathbf{A}$ shall be real and symmetric. The matrix is of type $n \times n$. There exist `n` eigenvalues $\{\lambda_1,\ \ldots, \lambda_n\}$ and unit length eigenvectors $\mathbf{v}_1,\ \ldots,\ \mathbf{v}_n$

For each pair of eigenvalues / eigenvectors we have:

$$
\mathbf{A} \cdot \mathbf{v}_j =  \lambda_j \cdot \mathbf{v}_j
$$

$\mathbf{A} \cdot \mathbf{v}_j$ are column vectors which can be interpreted as columns of a $n \times n$ matrix.

$$
\left[\begin{array}{cccc}
\vert & \vert &  & \vert \\
\mathbf{A} \cdot \mathbf{v}_1 & \mathbf{A} \cdot \mathbf{v}_2 & \ldots & \mathbf{A} \cdot \mathbf{v}_n \\
\vert & \vert &  & \vert \\
\end{array}\right] = \left[\begin{array}{cccc}
\vert & \vert &  & \vert \\
\lambda_1  \cdot \mathbf{v}_1 & \lambda_2 \cdot \mathbf{v}_2 & \ldots & \lambda_n \cdot \mathbf{v}_n \\
\vert & \vert &  & \vert \\
\end{array}\right]
$$

which can be expressed by a multiplication of matrices:

$$
\mathbf{A} \cdot \left[\begin{array}{cccc}
\vert & \vert &  & \vert \\
\mathbf{v}_1 & \mathbf{v}_2 & \ldots & \mathbf{v}_n \\
\vert & \vert &  & \vert \\
\end{array}\right] =
\left[\begin{array}{cccc}
\vert & \vert &  & \vert \\
\mathbf{v}_1 & \mathbf{v}_2 & \ldots & \mathbf{v}_n \\
\vert & \vert &  & \vert \\
\end{array}\right] \cdot \left[\begin{array}{cccc}
\lambda_1 &  &  & \\
 & \lambda_2 &  &  \\
  &  & \ddots &  \\
  &  &  & \lambda_n \\
\end{array}\right]
$$

Defining matrices $\mathbf{V}$ and $\mathbf{\Lambda}$ as:

$$
\mathbf{V} = \left[\begin{array}{cccc}
\vert & \vert &  & \vert \\
\lambda_1  \cdot \mathbf{v}_1 & \lambda_2 \cdot \mathbf{v}_2 & \ldots & \lambda_n \cdot \mathbf{v}_n \\
\vert & \vert &  & \vert \\
\end{array}\right]
$$

$$
\mathbf{\Lambda} = \left[\begin{array}{cccc}
\lambda_1 &  &  & \\
 & \lambda_2 &  &  \\
  &  & \ddots &  \\
  &  &  & \lambda_n \\
\end{array}\right]
$$

we get the compact form:

$$
\mathbf{A} \cdot \mathbf{V} = \mathbf{V} \cdot \mathbf{\Lambda} 
$$

All column vectors of matrix $\mathbf{V}$ are mutually orthonormal. This condition is equivalent to 

$$
\mathbf{V}^T \cdot \mathbf{V} = \mathbf{I}
$$

and we get:

$$\begin{gather}
\mathbf{A} \cdot \mathbf{V} \cdot \mathbf{V}^T = \mathbf{V} \cdot \mathbf{\Lambda} \cdot \mathbf{V}^T \\
\to \\
\mathbf{A} = \mathbf{V} \cdot \mathbf{\Lambda} \cdot \mathbf{V}^T
\end{gather}
$$

The last equation is also known as the `diagonalisation of a symmetric matrix`.

The equation can be written in different form:

$$\begin{gather}
\mathbf{A} = \left(\mathbf{V} \cdot \mathbf{\Lambda} \right) \cdot \mathbf{V}^T \\
\mathbf{A} = \left[\begin{array}{cccc}
\vert & \vert &  & \vert \\
\lambda_1  \cdot \mathbf{v}_1 & \lambda_2 \cdot \mathbf{v}_2 & \ldots & \lambda_n \cdot \mathbf{v}_n \\
\vert & \vert &  & \vert \\
\end{array}\right] \cdot \left[\begin{array}{ccc}
- & \mathbf{v}^T_1 & -\\
- & \mathbf{v}^T_2 &  - \\
 & \vdots &  \\
 - & \mathbf{v}^T_n & -
\end{array}\right]
\end{gather}
$$

$$
\mathbf{A} = \sum_{j=1}^{n} \lambda_j \cdot \mathbf{v}_j \cdot \mathbf{v}_j^T
$$

Matrix $\mathbf{A}$ can thus be expressed as sum `n` of partial matrices. Each partial matrix is the defined as outer product $\mathbf{v}_j \cdot \mathbf{v}_j^T$. Each partial matrix is of type $n \times n$.

---

## Matrix power 



Multiplying again by matrix $\mathbf{B}$ we get.

$$
\mathbf{B} \cdot  \mathbf{B} \cdot \mathbf{v} = \mathbf{B} \cdot \lambda \cdot \mathbf{v} = \lambda \cdot \mathbf{B} \cdot \mathbf{v} = \lambda^2 \cdot \mathbf{v}
$$

Thus the scaled vector $\lambda \cdot \mathbf{v}$ is again an eigenvector.

If matrix multiplication by $\mathbf{B}$ is applied `n` times the result is:

$$
\mathbf{B}^n \cdot \mathbf{v} = \lambda^n \cdot \mathbf{v}
$$

If $N \times N$ matrix $\mathbf{B}$ is symmetric there are $N$ linear independent eigenvectors. If we express a vector as a linear combination of eigenvectors the multiplication of a matrix with a vector is simply a weighted addition of the eigenvectors. Thus the matrix multiplication can be replaced by a less computational demanding addition of vectors.

Another useful properties is stated for a *positive definite* matrix $\mathbf{B}$ ->  ($\mathbf{v}^T \cdot \mathbf{B} \cdot \mathbf{v} \gt 0 $):

$$\begin{gather}
\mathbf{B} \cdot \mathbf{v} = \lambda \cdot \mathbf{v} \\
\underbrace{\mathbf{v}^T \cdot \mathbf{B} \cdot \mathbf{v}}_{\gt \ 0} = \lambda \cdot \underbrace{\mathbf{v}^T \cdot \mathbf{v}}_{\gt \ 0} \\
\
\to \lambda \gt 0
\end{gather}
$$

All eigenvalues are strictly positive.


---

### Special case / symmetric matrix

For a real and symmetric matrix $\mathbf{A}$ we want to get $\mathbf{A}^2$.

Since $\mathbf{A}$ can be `diagonalized`

$$
\mathbf{A} = \mathbf{V} \cdot \mathbf{\Lambda} \cdot \mathbf{V}^T
$$

we can express $\mathbf{A}^2$ by the product

$$\begin{gather}
\mathbf{A}^2 = \mathbf{A} \cdot \mathbf{A} = \mathbf{V} \cdot \mathbf{\Lambda} \cdot \mathbf{V}^T \cdot \mathbf{V} \cdot \mathbf{\Lambda} \cdot \mathbf{V}^T \\
\mathbf{A} \cdot \mathbf{A} = \mathbf{V} \cdot \mathbf{\Lambda} \cdot \mathbf{\Lambda} \cdot \mathbf{V}^T = \mathbf{V} \cdot \mathbf{\Lambda}^2 \cdot \mathbf{V}^T \\
\ \\
\mathbf{A}^2 = \mathbf{V} \cdot \mathbf{\Lambda}^2 \cdot \mathbf{V}^T 
\end{gather}
$$

and for the general case $\mathbf{A}^k$:

$$
\mathbf{A}^k = \mathbf{V} \cdot \mathbf{\Lambda}^k \cdot \mathbf{V}^T 
$$

$$
\mathbf{A}^k = \sum_{j=1}^{n} \lambda_j^k \cdot \mathbf{v}_j \cdot \mathbf{v}_j^T
$$

**matrix inverse**

If real symmetric matrix $\mathbf{A}$ has an inverse $\mathbf{A}^{-1}$ it can be evaluated like this:

$$\begin{gather}
\mathbf{A}^{-1} = \left(\mathbf{V} \cdot \mathbf{\Lambda} \cdot \mathbf{V}^T \right) \\
\mathbf{A}^{-1} = \left( \mathbf{V}^T \right)^{-1} \cdot \mathbf{\Lambda}^{-1} \cdot  \mathbf{V}^{-1} \\
\mathbf{A}^{-1} = \left( \mathbf{V}^{-1} \right)^{-1} \cdot \mathbf{\Lambda}^{-1} \cdot  \mathbf{V}^T \\
\mathbf{A}^{-1} = \mathbf{V} \cdot \mathbf{\Lambda}^{-1} \cdot  \mathbf{V}^T 
\end{gather}
$$

where matrix $\mathbf{\Lambda}^{-1}$ is just another diagonal matrix:

$$
\mathbf{\Lambda}^{-1} = \left[\begin{array}{cccc}
\frac{1}{\lambda_1} &  &  & \\
 & \frac{1}{\lambda_2} &  &  \\
  &  & \ddots &  \\
  &  &  & \frac{1}{\lambda_n} \\
\end{array}\right]
$$

---



## Symmetric positive definite matrix

Consider the expression

$$
\mathbf{x}^T \cdot \mathbf{A} \cdot \mathbf{x} = f(\mathbf{x})
$$

Since matrix $\mathbf{A}$ is real symmetric the quantity $\mathbf{x}$ is real.

$$\begin{gather}
\mathbf{x}^T \cdot \mathbf{A} \cdot \mathbf{x} = \sum_{j=1}^{n} \lambda_j \cdot \mathbf{x}^T \cdot \mathbf{v}_j \cdot \mathbf{v}_j^T \cdot \mathbf{x} \\
\ = \sum_{j=1}^{n} \lambda_j \cdot \mathbf{v}_j^T \cdot \mathbf{x} \cdot \mathbf{v}_j^T \cdot \mathbf{x} = \sum_{j=1}^{n} \lambda_j \cdot \left(\mathbf{v}_j^T \cdot \mathbf{x} \right)^2
\end{gather}
$$

We assume that eigenvalues are ordered in decreasing order: $\lambda_1 \ge \lambda_2 \ge \cdots \lambda_n$.

$$
\mathbf{x}^T \cdot \mathbf{A} \cdot \mathbf{x} = f(\mathbf{x}) \le  \lambda_1 \cdot \sum_{j=1}^{n} \left(\mathbf{v}_j^T \cdot \mathbf{x} \right)^2
$$

$$
\sum_{j=1}^{n} \left(\mathbf{v}_j^T \cdot \mathbf{x} \right)^2 = ||\mathbf{V} \cdot \mathbf{x} ||^2 = \left(\mathbf{V} \cdot \mathbf{x} \right)^T \cdot \left(\mathbf{V} \cdot \mathbf{x} \right) = \mathbf{x}^T \cdot \mathbf{V}^T \cdot \mathbf{V} \cdot \mathbf{x} = \mathbf{x}^T \cdot \mathbf{I} \cdot \mathbf{x} = \mathbf{x}^T \cdot \mathbf{x} = ||\mathbf{x}||^2
$$

$$
\mathbf{x}^T \cdot \mathbf{A} \cdot \mathbf{x}  \le  \lambda_1 \cdot \sum_{j=1}^{n} \left(\mathbf{v}_j^T \cdot \mathbf{x} \right)^2 = \lambda_1 \cdot  ||\mathbf{x}||^2
$$

For any vector $\mathbf{x}$ with init length we have

$$
\underset{||\mathbf{x}||^2 = 1}{\max} \ \mathbf{x}^T \cdot \mathbf{A} \cdot \mathbf{x}  \le \lambda_1
$$

For the specific case of $\mathbf{x}$ being an eigenvector $\mathbf{x} = \mathbf{v}_j$ we get:

$$
\mathbf{v}_j^T \cdot \mathbf{A} \cdot \mathbf{v}_j = \lambda_j \cdot \mathbf{v}_j^T \cdot \mathbf{v}_j = \lambda_j \cdot ||\mathbf{v}_j||^2 = \lambda_j
$$

from which it follows

$$
\underset{||\mathbf{x}||^2 = 1}{\max} \ \mathbf{x}^T \cdot \mathbf{A} \cdot \mathbf{x}  = \lambda_1
$$

For the minimum value a similar equation can be found:

$$
\underset{||\mathbf{x}||^2 = 1}{\min} \ \mathbf{x}^T \cdot \mathbf{A} \cdot \mathbf{x}  = \lambda_n
$$

**positive definite**

$$
\mathbf{x}^T \cdot \mathbf{A} \cdot \mathbf{x} \gt 0 
$$

All eigenvalues are <ins>strictly</ins> positive $\gt 0$.


**positive semi-definite**

$$
\mathbf{x}^T \cdot \mathbf{A} \cdot \mathbf{x} \ge 0
$$

All eigenvalue are <ins>non-negative</ins> $\ge 0$

---

## Example of eigenvector decomposition

Matrix $\mathbf{A}$ is defined as a $2 \times 3$ matrix.

$$
\mathbf{A} = \left[\begin{array}{ccc}
1 & 1 & 0 \\
0 & 1 & 1
\end{array}\right]
$$

A rectangular matrix has no eigendecomposition. However for the matrix product $\mathbf{A}^T \cdot \mathbf{A}$ which is a symmetric $3 \times 3$ matrix the eigendecomposition exists. 

1) its eigenvalues are real-valued

2) the eigenvector are mutually orthogonal

So lets compute (manually):

$$
\mathbf{B} = \mathbf{A}^T \cdot \mathbf{A}
$$

$$
\mathbf{B} = 
\left[\begin{array}{cc}
1 & 0 \\
1 & 1 \\
0 & 1
\end{array}\right]
\cdot
\left[\begin{array}{ccc}
1 & 1 & 0 \\
0 & 1 & 1
\end{array}\right] = \left[\begin{array}{ccc}
1 & 1 & 0 \\
1 & 2 & 1 \\
0 & 1 & 1
\end{array}\right] 
$$

The eigen decomposition of $\mathbf{B}$ can be expressed like this:

$$
\mathbf{B} = \mathbf{V} \cdot \mathbf{\Lambda} \cdot \mathbf{V}^T = \mathbf{V} \cdot \mathbf{\Lambda} \cdot \mathbf{V}^{-1}
$$

**computing the eigenvalues**

The eigenvalues are computed from the roots of the characteristic polynomial $p(\lambda)$.

$$
p(\lambda) = det \left[\begin{array}{ccc}
1-\lambda & 1 & 0 \\
1 & 2-\lambda & 1 \\
0 & 1 & 1-\lambda
\end{array}\right] = \lambda \cdot \left(1 - \lambda\right) \cdot \left(3 - \lambda\right)
$$

There are three real-valued distinct eigenvalues $\lambda_1 = 3,\ \lambda_2 = 1,\ \lambda_3 = 0$. For each the corresponding eigenvector is computed:

**computing eigenvectors**

For $\lambda_1 = 3$ the elements of eigenvector $\mathbf{v}_1$ are found solving this equation:

$$
\left[\begin{array}{ccc}
1-3 & 1 & 0 \\
1 & 2-3 & 1 \\
0 & 1 & 1-3
\end{array}\right] \cdot \left[\begin{array}{c}
x_1 \\ x_2 \\ x_3
\end{array}\right]
= \mathbf{0}
$$

$$
\mathbf{v}_1 = t \cdot \left[\begin{array}{c}
1 \\ 2 \\ 1
\end{array}\right] = t \cdot \sqrt{6} \cdot \left[\begin{array}{c}
\frac{1}{\sqrt{6}} \\ \frac{2}{\sqrt{6}} \\ \frac{1}{\sqrt{6}}
\end{array}\right]
$$

For $\lambda_2 = 1$ the elements of eigenvector $\mathbf{v}_2$ are found solving this equation:

$$
\left[\begin{array}{ccc}
1-1 & 1 & 0 \\
1 & 2-1 & 1 \\
0 & 1 & 1-1
\end{array}\right] \cdot \left[\begin{array}{c}
x_1 \\ x_2 \\ x_3
\end{array}\right]
= \mathbf{0}
$$

$$
\mathbf{v}_2 = t \cdot \left[\begin{array}{c}
-1 \\ 0 \\ 1
\end{array}\right] = t \cdot \sqrt{2} \cdot \left[\begin{array}{c}
\frac{-1}{\sqrt{2}} \\ 0 \\ \frac{1}{\sqrt{2}}
\end{array}\right]
$$

For $\lambda_3 = 0$ the elements of eigenvector $\mathbf{v}_3$ are found solving this equation:

$$
\left[\begin{array}{ccc}
1 & 1 & 0 \\
1 & 2 & 1 \\
0 & 1 & 1
\end{array}\right] \cdot \left[\begin{array}{c}
x_1 \\ x_2 \\ x_3
\end{array}\right]
= \mathbf{0}
$$

$$
\mathbf{v}_3 = t \cdot \left[\begin{array}{c}
1 \\ -1 \\ 1
\end{array}\right] = t \cdot \sqrt{3} \cdot \left[\begin{array}{c}
\frac{1}{\sqrt{3}} \\ \frac{-1}{\sqrt{3}} \\ \frac{1}{\sqrt{3}}
\end{array}\right]
$$

The eigenvectors $\mathbf{v}_1,\ \mathbf{v}_2,\ \mathbf{v}_3$ have been computed as vectors each with length $1$ and a unknown scaling factor.

Finally the orthogonal matrix $\mathbf{V}$ can be setup with the orthonormal eigenvectorrs as column vectors.

$$
\mathbf{V} = \left[\begin{array}{ccc}
\frac{1}{\sqrt{6}} & \frac{-1}{\sqrt{2}} &  \frac{1}{\sqrt{3}} \\
\frac{2}{\sqrt{6}} & 0 &  \frac{-1}{\sqrt{3}} \\
\frac{1}{\sqrt{6}} & \frac{1}{\sqrt{2}} &  \frac{1}{\sqrt{3}}
\end{array}\right]
$$

The column vectors of $\mathbf{V}$ are mutually orthonormal. The inverse matrix $\mathbf{V}^{-1}$ is just the transpose of $\mathbf{V}$.

Then the eigenvector decomposition of matrix $\mathbf{B}$ may be written like this:

$$\begin{gather}
\mathbf{B} = \mathbf{A}^T \cdot \mathbf{A} = \mathbf{V} \cdot \Lambda \cdot \mathbf{V}^T \\
\mathbf{B} = \left[\begin{array}{ccc}
\frac{1}{\sqrt{6}} & \frac{-1}{\sqrt{2}} &  \frac{1}{\sqrt{3}} \\
\frac{2}{\sqrt{6}} & 0 &  \frac{-1}{\sqrt{3}} \\
\frac{1}{\sqrt{6}} & \frac{1}{\sqrt{2}} &  \frac{1}{\sqrt{3}}
\end{array}\right] \cdot
\left[\begin{array}{ccc}
3 & 0 &  0 \\
0 & 1 &  0 \\
0 & 0 &  0
\end{array}\right] \cdot
\left[\begin{array}{ccc}
\frac{1}{\sqrt{6}} & \frac{2}{\sqrt{6}} &  \frac{1}{\sqrt{6}} \\
\frac{-1}{\sqrt{2}} & 0 &  \frac{1}{\sqrt{2}} \\
\frac{1}{\sqrt{3}} & \frac{-1}{\sqrt{3}} &  \frac{1}{\sqrt{3}}
\end{array}\right] 
\end{gather}
$$

$$\begin{gather}
\mathbf{B} = \left[\begin{array}{ccc}
\frac{1}{\sqrt{6}} & \frac{-1}{\sqrt{2}} &  \frac{1}{\sqrt{3}} \\
\frac{2}{\sqrt{6}} & 0 &  \frac{-1}{\sqrt{3}} \\
\frac{1}{\sqrt{6}} & \frac{1}{\sqrt{2}} &  \frac{1}{\sqrt{3}}
\end{array}\right] \cdot
\left[\begin{array}{ccc}
\frac{3}{\sqrt{6}} & \frac{6}{\sqrt{6}} &  \frac{3}{\sqrt{6}} \\
\frac{-1}{\sqrt{2}} & 0 &  \frac{1}{\sqrt{2}} \\
0 & 0 & 0
\end{array}\right] =
\left[\begin{array}{ccc}
1 & 1 & 0 \\
1 & 2 & 1 \\
0 & 1 & 1
\end{array}\right]
\end{gather}
$$

And here comes the numerical computation (much easier than the manual work).

In [16]:
Amat = np.array([[1, 1, 0], [0, 1, 1]])
Bmat = Amat.T @ Amat
lambda_list, Vmat = np.linalg.eig(Bmat)
lambda_mat = np.diag(lambda_list)

Bmat_from_decomposition = Vmat @ lambda_mat @ Vmat.T

print(f"Amat :\n{Amat}\n")
print(f"Bmat :\n{Bmat}\n")
print(f"lambda_list :\n{lambda_list}\n")                         
print(f"Vmat :\n{Vmat}\n")    
print(f"Bmat_from_decomposition :\n{Bmat_from_decomposition}")

Amat :
[[1 1 0]
 [0 1 1]]

Bmat :
[[1 1 0]
 [1 2 1]
 [0 1 1]]

lambda_list :
[ 3.00000000e+00  1.00000000e+00 -3.36770206e-17]

Vmat :
[[-4.08248290e-01  7.07106781e-01  5.77350269e-01]
 [-8.16496581e-01  2.61239546e-16 -5.77350269e-01]
 [-4.08248290e-01 -7.07106781e-01  5.77350269e-01]]

Bmat_from_decomposition :
[[ 1.00000000e+00  1.00000000e+00 -2.33270278e-16]
 [ 1.00000000e+00  2.00000000e+00  1.00000000e+00]
 [-1.77759127e-16  1.00000000e+00  1.00000000e+00]]
